name: Sync Backend to Hugging Face
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push Backend Subfolder to HuggingFace
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: thomasso/betuveto-api
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: 'space'
          private: 'false'
          space_sdk: 'gradio'
          subdirectory: 'backend'
